In [22]:
import numpy as n
x=n.array([[1,2,3],[4,5,6]])
print(x)
#print(x[0])
#print(x[1])
print(x[:,1])

[[1 2 3]
 [4 5 6]]
[2 5]


In [14]:
n.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [12]:
print(n.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
a=n.repeat([1,2,3,4],3)
print(a)

[1 1 1 2 2 2 3 3 3 4 4 4]


In [7]:
d=n.array([1,2,3,4])
print(n.array([d,pow(d,4)]))

[[  1   2   3   4]
 [  1  16  81 256]]


In [ ]:
import numpy
print(numpy.eye(4,dtype=int))


In [ ]:
import random 
import numpy as n
d=n.random.randint(1,30,(3,3))
print(d)
print("the max",d.max())
print("the min",d.min())
print("standard deviation",d.std())
print("mean",d.mean())
print("median",n.median(d))
print("mod",n.mod(2,3))
print(d.transpose())


In [ ]:
import random 
import numpy as n
n.random.normal(5,4,10)

In [ ]:
import numpy as n
a=n.array([3,5,7,9])
print(a)
print(a.mean())
print(n.median(a))
print(n.mod(2,3))

In [ ]:
import numpy as n
a=n.array([3,5,7,9])
a.std()

In [ ]:
import numpy as n
a=n.array([3,5,7,9])
b=n.array([2,4,6,8])
print(n.vstack((a)))
print(n.hstack((a,b)))

In [ ]:
import numpy as n
a=n.array([[1,2,3,4],[6,7,8,9]])
print(a)
print(a.flatten())

In [ ]:
import numpy as n
a=n.array([[1,2,3,4],[6,7,8,9]])
print(a)
print(a.reshape((4,2)))

In [ ]:
import numpy as n
print(n.ones((3,2),dtype=int))

In [ ]:
import numpy as n
print(n.zeros((3,2),dtype=float))

In [ ]:
import numpy as n
b=n.array([[1.1,1.2,1.3,1.4],[2.1,2.2,2.3,2.4]])
print(n.shape(b))
print(b.dtype)

In [ ]:
import numpy as n
a=n.array([[1,2,3,4],[5,6,7,8]])
print(n.shape(a))
print(a.dtype)

In [ ]:
import numpy as n
a=n.array([3,5,7,9])
b=n.array([2,4,6,8])
print(a*b)
print(a/b)
print(a%b)

In [ ]:
import numpy as n
a=n.array([3,5,7,9])
b=n.array([2,4,6,8])
print(a+b)
print(a-b)

In [ ]:
import numpy as n
print(n.array([[2,4,6,8],[1,2,3,4]]))

In [ ]:
import numpy as n
print(n.array([2,4,6,8]))

In [ ]:
import numpy as n
print(n.__version__)